In [1]:
import numpy as np
import pandas as pd

In [14]:
df = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv",usecols=['name','seller_type','transmission','owner','fuel'])

In [15]:
df.head()

                       name    fuel seller_type transmission         owner
0             Maruti 800 AC  Petrol  Individual       Manual   First Owner
1  Maruti Wagon R LXI Minor  Petrol  Individual       Manual   First Owner
2      Hyundai Verna 1.6 SX  Diesel  Individual       Manual   First Owner
3    Datsun RediGO T Option  Petrol  Individual       Manual   First Owner
4     Honda Amaze VX i-DTEC  Diesel  Individual       Manual  Second Owner

# To summarize:

Ordinal Variables ---> OrdinalEcoder: Owner,, Seller_type, Transmission                            
Target or label Variables---> LabelEncoder: Fuel

# Using Python

In [16]:
df.drop('name',axis=1,inplace=True)

In [18]:
df['transmission'] = df['transmission'].map({'Manual':0,'Automatic':1})

In [20]:
df['seller_type'] = df['seller_type'].map({'Individual':0,'Dealer':1,'Trustmark Dealer':2})

In [22]:
df['transmission'].apply(lambda x: 1 if x=='Manual' else 0)

0       0
1       0
2       0
3       0
4       0
       ..
4335    0
4336    0
4337    0
4338    0
4339    0
Name: transmission, Length: 4340, dtype: int64

In [23]:
df

        fuel  seller_type  transmission         owner
0     Petrol            0             0   First Owner
1     Petrol            0             0   First Owner
2     Diesel            0             0   First Owner
3     Petrol            0             0   First Owner
4     Diesel            0             0  Second Owner
...      ...          ...           ...           ...
4335  Diesel            0             0  Second Owner
4336  Diesel            0             0  Second Owner
4337  Petrol            0             0  Second Owner
4338  Diesel            0             0   First Owner
4339  Petrol            0             0   First Owner

[4340 rows x 4 columns]

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train, X_test, y_train, y_test = train_test_split(df.drop('fuel',axis=1),df['fuel'], test_size=0.2, random_state=42)

# Using Scikitlearn

In [27]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

# 1 Applying Label Encoder

In [28]:
le = LabelEncoder()

In [29]:
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.transform(y_test)

In [30]:
y_train_scaled

array([1, 1, 4, ..., 1, 1, 4], shape=(3472,))

In [31]:
oe = OrdinalEncoder()
X_train_traf= oe.fit_transform(X_train)
X_test_traf = oe.transform(X_test)

In [32]:
X_train.head(3)

      seller_type  transmission         owner
227             0             0   First Owner
964             0             0   First Owner
2045            0             0  Second Owner

In [33]:
X_train_traf

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 2.],
       ...,
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], shape=(3472, 3))